Default: &defaults
  host: "localhost"
  port: 3000
  copyright: suztomo

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://osojiphoto.com"
  <<: *defaults